### ISSUE TITLE
Wow this is cool!!! Thanks you!

### ISSUE THREAD

**Issue by YouMoMCallME** [Monsterfisch/StrongholdsOfConquest_#1]
Your work is very impressive! I really like it. Thanks you....

Thanks for the translation .aic.
If you want, I could translate the next versions.

By the way, you could talk to the author of Stronghold Europe and ask him for textures from Stronghold 1.

**Comment by Monsterfisch** [comment]
That would be great I assume the google translated version is a bit dodgy but that was to be expected ^^

**Comment by YouMoMCallME** [comment]
In your texture pack there are no new textures of towers and Water Pot...

**Comment by Monsterfisch** [comment]
the image files are in a separate zip file (its not listed in the release as its not really complete) you can get it from [here ](https://github.com/Monsterfisch/StrongholdsOfConquest_/blob/master/StrongholdsOfConquest_VisualEdit.zip)

**Comment by YouMoMCallME** [comment]
> the image files are in a separate zip file (its not listed in the release as its not really complete) you can get it from [here](https://github.com/Monsterfisch/StrongholdsOfConquest_/blob/master/StrongholdsOfConquest_VisualEdit.zip)

Thank you very much
