### ISSUE TITLE
An exquisite collection of minor nitpicks and other bugs

### ISSUE THREAD

**Issue by Heroesflorian** [Monsterfisch/StrongholdsOfConquest_#2]
This is a collection of various issues found while testing (and will be extended in the future). 

**General:**
- For multi-layered castles, I suggest arranging tower ballistae spots so that those on the inner ring are manned first, then the outer ring's ballistae spots (and forward-facing ones before back-facing ones in the same ring, although that is already the case, I think). 

**Abbot:**
- abbot4.aiv: 
  - Fletchers are too few / far away, causing the Abbot to be always short on bows, and he always only buys 2 bows at once... together, this seems to cause him to be short on archers too often, even when he has some gold. 
  ![grafik](https://user-images.githubusercontent.com/12549394/100529294-55673b80-31e6-11eb-81f8-96b833f5b5d7.png)
  - As you can see, his inner ring's forward gate is closed when the outer ring is attacked. This causes an economic lockdown. Might be avoidable if the distance between outer ring wall and inner ring gate is slightly increased. 
  - The outer ring's front wall is amended by some low stairs, on which some oil engineer spots are placed. Nice idea, but those engineers are too vulnerable I think, being the furthest forward defensive units (except the 2 FBals) and without evelation protection. 
  - The inner ring's back gate seems to be the only thing that vaguely covers the back side wall... there's some safespots for attackers on the back. Also, that gate is accessible from the outside if one of the non-crenelated tiles of wall is damaged slightly... this seems to happen more frequently than I'd have expected. 
  ![grafik](https://user-images.githubusercontent.com/12549394/100529544-ffe05e00-31e8-11eb-8488-cea8f92ad632.png)

Marshal:
- marshal??.aiv: 
  ![grafik](https://user-images.githubusercontent.com/12549394/100557200-cb7fa700-32a7-11eb-99eb-7f16d4e85a7f.png)
  As you can see, this one has all sorts of fancy and expensive fortifications set up, yet his inner castle ring is still wide open due to a missing tower. I think some slight adjustments in the build order could be helpful there. 
- marshal?.aiv:
  ![grafik](https://user-images.githubusercontent.com/12549394/100943871-5e198380-34fe-11eb-9aa5-8d8373b95ab1.png)
  If the tower gets destroyed, one workshop and one stable will be demolished due to becoming unreachable. That's not a desirable property for a front-facing tower to have. 

Nizar: 
- nizar3.aiv:
  ![grafik](https://user-images.githubusercontent.com/12549394/100940353-0d9f2780-34f8-11eb-808b-c0803d243a3c.png)
  As you can see, this castle already has all kinds of towers and fortifications, yet the campfire is not enclosed yet (inner small gate there still was not built yet). 

Phillip:
- Can get stuck at full armoury with weapon makers waiting for storage space in castles with only 1 armoury. Either needs a 2nd armoury or lower effective max amount of stored goods. 

**Rat:** 
- European archers for attacks seem too passive (like backup units?).

**Comment by Monsterfisch** [comment]
At this point, I think all of these have basically been addressed with the upcomming changes.
